# 
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     
#                                                             

# format = '''
# $username$directory$git_branch$cmd_duration
# $character'''

[username]
style_user = 'bold purple'
style_root = 'bold bright-red'
format = '[$user]($style) in '

[character]
success_symbol = '[>](bold green)'
error_symbol = '[X](bold bright-red)'

[directory]
style = 'bold purple'
truncation_length = 5
truncation_symbol = ''
truncate_to_repo = true
read_only = ' [ro] '
read_only_style = 'bold bright-cyan'
home_symbol = '~'
repo_root_format = '[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
min_time = 1000
format = '[took ](bold white)[$duration](bold bright-yellow)' 

[sudo]
disabled = true
format = 'sudo'
style = 'bold bright-yellow'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M'
style = 'bold white'

# 
# ┌─┐┬ ┬┌┬┐┌┐ ┌─┐┬  ┌─┐
# └─┐└┬┘│││├┴┐│ ││  └─┐
# └─┘ ┴ ┴ ┴└─┘└─┘┴─┘└─┘
#

[aws]
symbol = "aws "

[buf]
symbol = "buf "

[c]
symbol = "c "

[cmake]
symbol = "cmk "

[conda]
symbol = "cnd "

[crystal]
symbol = "crs "

[dart]
symbol = "drt "

[docker_context]
symbol = "dckr "

[elixir]
symbol = "exs "

[elm]
symbol = "els "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fsl "

[git_branch]
symbol = "git "
style = 'bold bright-cyan'

[git_commit]
tag_symbol = 'gcm '

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
style = 'bold bright-yellow'

[golang]
symbol = "go "

[guix_shell]
symbol = "guix "

[haskell]
symbol = "hskl "

[haxe]
symbol = "hx "

[hg_branch]
symbol = "hg "

[hostname]
ssh_symbol = "ssh "

[java]
symbol = "jv "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "
style = 'bold bright-cyan'
detect_extensions = ['lua']

[memory_usage]
disabled = false
symbol = "mem  "
style = 'bold bright-red'
threshold = 80

[meson]
symbol = "msn "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[nodejs]
symbol = "node.js "

[ocaml]
symbol = "ml "

[os.symbols]
AIX = "aix "
Alpaquita = "alq "
AlmaLinux = "alma "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CachyOS = "cach "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Kali = "kali "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
Nobara = "nbra "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
RockyLinux = "rky "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Ultramarine = "ultm "
Unknown = "unk "
Uos = "uos "
Void = "void "
Windows = "win "

[package]
symbol = "pkg "

[perl]
symbol = "perl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pjl "

[python]
symbol = "py "
style = 'bold bright-cyan'
detect_extensions = ["py"]

[rlang]
symbol = "R "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scl "

[swift]
symbol = "swft "

[zig]
symbol = "zig "

[gradle]
symbol = "grdl "
