# 
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     
#                                                             

# format = '''
# $username$directory$git_branch$cmd_duration
# $character'''

[username]
style_user = 'bold purple'
style_root = 'bold bright-red'
format = '[]($style) [$user]($style) in '

[character]
success_symbol = '[ ](bold green)'
error_symbol = '[ ](bold bright-red)'

[directory]
style = 'bold purple'
truncation_length = 10
truncation_symbol = ''
truncate_to_repo = true
read_only = '  '
read_only_style = 'bold cyan'
home_symbol = '~'
repo_root_format = '[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
min_time = 5000
format = '[took ](italic)[$duration](bold italic bright-yellow)' 

[sudo]
disabled = false
format = '[  ]($style)'
style = 'bold bright-yellow'

# 
# ┌─┐┬ ┬┌┬┐┌┐ ┌─┐┬  ┌─┐
# └─┐└┬┘│││├┴┐│ ││  └─┐
# └─┘ ┴ ┴ ┴└─┘└─┘┴─┘└─┘
#

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
style = 'bold cyan'

[git_commit]
tag_symbol = '  '

[git_status]
style = 'bold bright-yellow'

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "
style = 'bold cyan'
detect_extensions = ['lua']

[memory_usage]
disabled = false
symbol = "  "
style = 'bold bright-red'
threshold = 80

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = 'bold cyan'

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
style = 'bold cyan'
detect_extensions = ["py"]

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
