#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
                                                             
#
# ┬┌─┌─┐┬ ┬┌─┐
# ├┴┐├┤ └┬┘└─┐
# ┴ ┴└─┘ ┴ └─┘
#

pgrep -x sxhkd > /dev/null || sxhkd &

# 
# ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
# ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐
# └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘
# 

bspc monitor -d 󰉋 󰇧 󰋩 󰋋 󰈙 # 󰆦

# 
# ┌─┐┌─┐┌─┐┌─┐┌─┐┬─┐┌─┐┌┐┌┌─┐┌─┐
# ├─┤├─┘├─┘├┤ ├─┤├┬┘├─┤││││  ├┤ 
# ┴ ┴┴  ┴  └─┘┴ ┴┴└─┴ ┴┘└┘└─┘└─┘
# 

bspc config border_width         3
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true


# bspc config top_padding          32     # uncomment for a floating fanel


# bspc config focused_border_color "#ff8a18"
bspc config focused_border_color "#ffffff"


# 
# ┬ ┬┬┌┐┌┌┬┐┌─┐┬ ┬  ┬─┐┬ ┬┬  ┌─┐┌─┐
# │││││││ │││ ││││  ├┬┘│ ││  ├┤ └─┐
# └┴┘┴┘└┘─┴┘└─┘└┴┘  ┴└─└─┘┴─┘└─┘└─┘
#

bspc rule -a gimp-2.10 desktop='^3' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=pseudo_tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a libreoffice-writer desktop='^5' follow=on
bspc rule -a libreoffice-calc desktop='^5' follow=on
bspc rule -a libreoffice-impress desktop='^5' follow=on
bspc rule -a feh desktop='^3' state=pseudo_tiled follow=on
bspc rule -a Nitrogen state=pseudo_tiled
bspc rule -a Lxappearance state=floating
bspc rule -a mpv state=fullscreen
bspc rule -a Qalculate-gtk state=pseudo_tiled
bspc rule -a pavucontrol state=pseudo_tiled
bspc rule -a Butt_FLTK state=pseudo_tiled
bspc rule -a Zathura desktop='^5' follow=on
bspc rule -a Yad-icon-browser state=pseudo_tiled
bspc rule -a Spotify desktop='^4' follow=on
bspc rule -a MPlayer desktop='^3' state=fullscreen follow=on

# 
# ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ├─┤│ │ │ │ │└─┐ │ ├─┤├┬┘ │ 
# ┴ ┴└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴ 
# 

killall redshift ;
xrandr -s 1920x1080 &
feh --bg-fill ~/Pictures/Wallpapers/clouds.png &
# if [[ $(date +%H%M) -ge 0800 && $(date +%H%M) -lt 1800 ]]; then
#     feh --bg-fill ~/Pictures/Wallpapers/forest\ wallpaper\ day.jpg
# else
#     feh --bg-fill ~/Pictures/Wallpapers/forest\ wallpaper\ night.jpg
# fi &
~/.config/polybar/launch.sh &
redshift &
picom -b &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
dunst -c ~/.config/dunst/dunstrc &
xset -dpms &
xset s off &
notify-send 'Welcome astronaut!' 'If you need help, press Super + F1.' -i rocket
