#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║     
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║     
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
                                                             
#
# ┬┌─┌─┐┬ ┬┌─┐
# ├┴┐├┤ └┬┘└─┐
# ┴ ┴└─┘ ┴ └─┘
#

pgrep -x sxhkd > /dev/null || sxhkd &

# 
# ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
# ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐
# └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘
# 

bspc monitor -d 󰉋 󰇧 󰋩 󰋋 󰈙 󰆦

# 
# ┌─┐┌─┐┌─┐┌─┐┌─┐┬─┐┌─┐┌┐┌┌─┐┌─┐
# ├─┤├─┘├─┘├┤ ├─┤├┬┘├─┤││││  ├┤ 
# ┴ ┴┴  ┴  └─┘┴ ┴┴└─┴ ┴┘└┘└─┘└─┘
# 

bspc config border_width         3
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config top_padding          32     # comment out for a floating fanel


# bspc config focused_border_color "#ff8a18"
bspc config focused_border_color "#ffffff"


# 
# ┬ ┬┬┌┐┌┌┬┐┌─┐┬ ┬  ┬─┐┬ ┬┬  ┌─┐┌─┐
# │││││││ │││ ││││  ├┬┘│ ││  ├┤ └─┐
# └┴┘┴┘└┘─┴┘└─┘└┴┘  ┴└─└─┘┴─┘└─┘└─┘
#

bspc rule -a gimp-2.10 desktop='^3' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a libreoffice-writer desktop='^5' follow=on
bspc rule -a libreoffice-calc desktop='^5' follow=on
bspc rule -a libreoffice-impress desktop='^5' follow=on
bspc rule -a feh desktop='^3' state=floating follow=on
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a mpv desktop='^3' state=fullscreen follow=on
bspc rule -a Qalculate-gtk state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Butt_FLTK state=floating
bspc rule -a Zathura desktop='^5' follow=on
bspc rule -a Yad-icon-browser state=floating
bspc rule -a Spotify desktop='^4' follow=on

# 
# ┌─┐┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
# ├─┤│ │ │ │ │└─┐ │ ├─┤├┬┘ │ 
# ┴ ┴└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴ 
# 

xrandr -s 1920x1080 &
redshift &
# picom -b &
nitrogen --restore &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
dunst -c ~/.config/dunst/dunstrc &
